create table product_category
(
    id       bigint generated by default as identity
        constraint product_category_pk
            primary key,
    category varchar(40) not null
);

create table products
(
    id                  bigserial
        constraint products_pk
            primary key,
    name                varchar(50) not null,
    price               numeric     not null,
    product_category_id bigint      not null
        constraint products_product_category_id_fk
            references product_category
            on update cascade on delete cascade,
    info                varchar(1500)
);

create table users
(
    id       bigserial
        constraint users_pk
            primary key,
    login    varchar(30) not null,
    password varchar(100) not null,
    name     varchar(30) not null,
    surname  varchar(30) not null,
    email    varchar(50) not null
        constraint users_pk2
            unique,
    birthday date        not null
);

create table carts
(
    id         bigserial
        constraint carts_pk
            primary key,
    user_id    bigint            not null
        constraint carts_users_id_fk
            references public.users
            on update cascade on delete cascade,
    product_id bigint            not null
        constraint carts_products_id_fk
            references public.products
            on update cascade on delete cascade,
    cart       boolean,
    favorite   boolean,
    count      integer default 1 not null
);

create table orders
(
    id      bigserial
        constraint orders_pk
            primary key,
    name    varchar(50) not null,
    date    date        not null,
    user_id integer     not null
        constraint orders_users_id_fk
            references users
            on update cascade on delete cascade
);

create table order_product
(
    order_id   bigint not null
        constraint order_product_orders_id_fk
            references orders
            on update cascade on delete cascade,
    product_id bigint not null
        constraint order_product_products_id_fk
            references products
            on update cascade on delete cascade,
    id         bigserial
        constraint order_product_pk
            primary key
);